config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :events
  root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'users/:id' => 'users#show'
  resources :users, only: [:show]
  resources :attendee, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  validates :date, presence: true
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_many :attendees

  scope :past, -> { where('datetime < ?', Time.zone.now) }
  scope :future, -> { where('datetime >= ?', Time.zone.now) }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable, :confirmable and :activatable

  # Setup accessible (or protected) attributes for your model
  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :attendees
  has_many :attended_events, through: :attendees, foreign_key: 'event_id', source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendee_controller.rb
class AttendeeController < ApplicationController
  def create
    @attend = Attendee.new(params.require(:attendee).permit(:user_id, :event_id))
    meme = Attendee.all.where(event_id: @attend.event_id, user_id: current_user.id)
    # current_user.attendees.include?(lol)
    if meme.empty?
      @attend.save
      redirect_back(fallback_location: root_path)
    else
      puts('error')
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @attend = Attendee.new
    @events = Event.all
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.created_events.build(event_params)
    puts('try again') if @event.save

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else

        format.html { redirect_to new_event_path }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[new show index]
  skip_before_action :verify_authenticity_token

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:post)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def acount_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @event = Event.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendee_helper.rb
module AttendeeHelper
end

app/helpers/events_helper.rb
# rubocop:disable Style/GuardClause
module EventsHelper
  def timer(creator, user, c_date, lol)
    if creator == user
      if c_date > Time.zone.now
        nil
      else
        lol
      end
    end
  end

  def timer2(creator, user, c_date, lol)
    lol if creator == user && c_date > Time.zone.now
  end

  def if_nil(lol)
    array = []
    lol.each do |meme|
      array.push(meme) unless meme.nil?
    end
    array
  end
end
# rubocop:enable Style/GuardClause

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
# rubocop:disable Style/IfUnlessModifier

module PostsHelper
  def check
    @posts.each do |post|
      concat content_tag(:tr, content_tag(:td, post.post) + content_tag(:td, (if user_signed_in?
                                                                                post.user.email
                                                                              end)) + content_tag(:td, (link_to 'Show', post)) + content_tag(:td, content_tag(:td, (link_to 'Show', post))) + content_tag(:td, (link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' })))
    end
  end
end

# rubocop:enable Style/IfUnlessModifier

app/helpers/users_helper.rb
module UsersHelper
  #  def timer(creator, user, c_date, lol)
  #    if creator == user
  #      if c_date > Time.zone.now
  #        nil
  #      else
  #        lol
  #      end
  #    end
  #  end
  #
  #  def timer2(creator, user, c_date, lol)
  #    lol if creator == user && c_date > Time.zone.now
  #  end
  #
  #  def if_nil(lol)
  #    array = []
  #    lol.each do |meme|
  #      array.push(meme) unless meme.nil?
  #    end
  #    array
  #  end

  def timer_e(c_date, lol)
    if c_date > Time.zone.now
      nil
    else
      lol
    end
  end

  def timer2_e(c_date, lol)
    lol if c_date > Time.zone.now
  end

  def if_nil(lol)
    array = []
    lol.each do |meme|
      array.push(meme) unless meme.nil?
    end
    array
  end
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_field :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% past = Array.new %>
    <% future = Array.new %>
    <% @events.each do |event| %>
        <% past.push(timer_e(event.date, event)) %>
        <% future.push(timer2_e(event.date, event)) %>
    <% end %>

    <td><strong> Past <strong></td>
    <% past = if_nil(past) %>
    <% past.each do |shark| %>
      <tr>
          <td><%= shark.date %></td>
          <td><%= link_to 'Show', shark %></td>


      </tr>
    <% end %>

        <td><strong> Future <strong></td>
        <% future = if_nil(future) %>
        <% future.each do |shark| %>
        <tr>
          <td><%= shark.date %></td>
          <td><%= link_to 'Show', shark %></td>

        </tr>
        <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>
<%= link_to 'Back', root_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>USER:</strong>
  <strong><%= @event.creator.email %></strong>
</p>

<% @events.each do |event| %>
      <tr>
        <td>
            <% if event.id.to_i == params[:id].to_i %>
              <% event.attendees.each do |lol| %>
                <%= lol.user.email %> <br>
              <% end %>
            <% else %>
            <% end %>
        </td>
      </tr>
<% end %>

<%= form_with model: @attend, url: attendee_index_path do |form| %>
  <%= form.hidden_field :user_id, :value => current_user.id %>
  <%= form.hidden_field :event_id, :value => params[:id] %>

  <%= form.submit %>
<% end %>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>

<% if current_user != nil %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <%= link_to "User", user_url(current_user.id) , method: :get, :class => 'navbar-link' %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
  <%= link_to "Events", events_path, :class => 'navbar-link' %>
</p>

app/views/posts/_form.html.erb
<form action="/posts" accept-charset="UTF-8" method="POST">
  <input type="hidden" name="authenticity_token" value="<%# form_authenticity_token %>">

  <label for="fpost">Username</label>
  <input type="text" id="fpost" name="post[post]"><br><br>
  <input type="submit" value="Submit">
</form>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        

<% else %>
  <%= link_to('Login', new_user_session_path) %>  

<% end %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% check %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>

<% else %>
  <%= link_to('Login', new_user_session_path) %>

<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        

<% else %>
  <%= link_to('Login', new_user_session_path) %>  

<% end %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post.post %>
</p>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        

<% else %>
  <%= link_to('Login', new_user_session_path) %>  

<% end %>

app/views/users/show.html.erb
<%= @user.email %>
<% past = Array.new %>
<% future = Array.new %>
<% @event.each do |user|%>
<table>
<tbody>
  <% past.push(timer(user.creator_id, current_user.id, user.date, user)) %>
  <% future.push(timer2(user.creator_id, current_user.id, user.date, user)) %>

<% end %>
  <td>
    <td><strong> Future <strong></td>
    <% future = if_nil(future) %>
    <% future.each do |lol| %>
      <tr>
      <td><%= lol.date %> </td>
      <td><%= link_to 'show', lol %></td>
      </tr>
    <% end %>
  </td>

  <td>
    <td><strong> Past <strong></td>
    <% past = if_nil(past) %>
    <% past.each do |lol| %>
      <tr>
      <td><%= lol.date %> </td>
      <td><%= link_to 'show', lol %></td>
      </tr>
    <% end %>
  </td>


    <td>
      <td><strong> Attend <strong></td>
      <% @user.attendees.each do |meme| %>
      <tr>
      <td><%= meme.event.date %></td>
      <td><%= link_to 'show', meme.event %></td>
      </tr>
      <% end %>

    </td>

    </tbody>
</table>
<%= link_to 'Back', root_path %>